version: "3.8"
services:
  frontend:
    image: ghcr.io/typper-io/typper-bi-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_SERVICE_ACCOUNT_EMAIL: ${NEXT_PUBLIC_SERVICE_ACCOUNT_EMAIL}

  backend:
    image: ghcr.io/typper-io/typper-bi-backend:latest
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_AWS_ACCESS_KEY: ${SECRET_AWS_ACCESS_KEY}
      SECRET_AWS_SECRET_KEY: ${SECRET_AWS_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
      API_KEY: ${API_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      IV: ${IV}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      EMAIL_DOMAIN: ${EMAIL_DOMAIN}
      APP_DOMAIN: ${APP_DOMAIN}
      DATASOURCE_S3_BUCKET_NAME: ${DATASOURCE_S3_BUCKET_NAME}
      WORKSPACE_IMAGES_BUCKET_NAME: ${WORKSPACE_IMAGES_BUCKET_NAME}
      AWS_SSM_SECRET_PREFIX: ${AWS_SSM_SECRET_PREFIX}
      DEMO_ASSISTANT_ID: ${DEMO_ASSISTANT_ID}
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-storage:/var/lib/postgresql/data

volumes:
  postgres-storage:
    external: true
