services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  client:
    image: ghcr.io/typper-io/typper-bi-client:main
    ports:
      - "3000:3000"
    env_file:
      - .client.env

  server:
    image: ghcr.io/typper-io/typper-bi-server:main
    ports:
      - "3001:3001"
    env_file:
      - .server.env
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: