version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  client:
    image: ghcr.io/typper-io/typper-bi-client:main
    env_file:
      - .client.env
    networks:
      - backend

  server:
    image: ghcr.io/typper-io/typper-bi-server:main
    env_file:
      - .server.env
    depends_on:
      - db
    networks:
      - backend

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
