export const loadingPhrases = [
  'Loading, please wait...',
  'Preparing everything for you...',
  'Almost there...',
  'Just a moment...',
  'Processing your request...',
  'Almost ready...',
  "Hang tight, we're almost finished...",
  'Setting up your experience...',
  'Finalizing the details...',
  'A bit more patience, please...',
  'Loading, please wait...',
  'Getting everything ready for you...',
  'Almost there...',
  'Hold on a moment...',
  'Processing your request...',
  'Nearly ready...',
  'Please wait, we are finishing up...',
  'Setting up your experience...',
  'Wrapping up the details...',
  'A little more patience...',
]
